/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/denise/catkin_ws/src/camera_magnet/msg/xyReal.msg
 *
 */


#ifndef CAMERA_MAGNET_MESSAGE_XYREAL_H
#define CAMERA_MAGNET_MESSAGE_XYREAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_magnet
{
template <class ContainerAllocator>
struct xyReal_
{
  typedef xyReal_<ContainerAllocator> Type;

  xyReal_()
    : leftx(0.0)
    , lefty(0.0)
    , rightx(0.0)
    , righty(0.0)  {
    }
  xyReal_(const ContainerAllocator& _alloc)
    : leftx(0.0)
    , lefty(0.0)
    , rightx(0.0)
    , righty(0.0)  {
    }



   typedef double _leftx_type;
  _leftx_type leftx;

   typedef double _lefty_type;
  _lefty_type lefty;

   typedef double _rightx_type;
  _rightx_type rightx;

   typedef double _righty_type;
  _righty_type righty;




  typedef boost::shared_ptr< ::camera_magnet::xyReal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_magnet::xyReal_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct xyReal_

typedef ::camera_magnet::xyReal_<std::allocator<void> > xyReal;

typedef boost::shared_ptr< ::camera_magnet::xyReal > xyRealPtr;
typedef boost::shared_ptr< ::camera_magnet::xyReal const> xyRealConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_magnet::xyReal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_magnet::xyReal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_magnet

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'camera_magnet': ['/home/denise/catkin_ws/src/camera_magnet/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_magnet::xyReal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_magnet::xyReal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_magnet::xyReal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_magnet::xyReal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_magnet::xyReal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_magnet::xyReal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_magnet::xyReal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2817f9d509a8e395a72b46bdcca5d64b";
  }

  static const char* value(const ::camera_magnet::xyReal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2817f9d509a8e395ULL;
  static const uint64_t static_value2 = 0xa72b46bdcca5d64bULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_magnet::xyReal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_magnet/xyReal";
  }

  static const char* value(const ::camera_magnet::xyReal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_magnet::xyReal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 leftx\n\
float64 lefty\n\
float64 rightx\n\
float64 righty\n\
\n\
\n\
";
  }

  static const char* value(const ::camera_magnet::xyReal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_magnet::xyReal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftx);
      stream.next(m.lefty);
      stream.next(m.rightx);
      stream.next(m.righty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct xyReal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_magnet::xyReal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_magnet::xyReal_<ContainerAllocator>& v)
  {
    s << indent << "leftx: ";
    Printer<double>::stream(s, indent + "  ", v.leftx);
    s << indent << "lefty: ";
    Printer<double>::stream(s, indent + "  ", v.lefty);
    s << indent << "rightx: ";
    Printer<double>::stream(s, indent + "  ", v.rightx);
    s << indent << "righty: ";
    Printer<double>::stream(s, indent + "  ", v.righty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MAGNET_MESSAGE_XYREAL_H
